function fmtStat(val, key) {
  if (val === null || val === undefined || val === "" || (typeof val === "number" && isNaN(val)) || val === "NaN") return "—";
  const pct = ["fg_pct", "ft_pct", "3p_pct"];
  if (pct.includes(key)) return `${Number(val).toFixed(1)}%`;
  return Number(val) % 1 === 0 ? Number(val).toFixed(0) : Number(val).toFixed(1);
}

/**
 * Export the projected roster as a print-ready PDF page.
 *
 * @param {object} opts
 * @param {string}   opts.team           - Program name
 * @param {object}   opts.settings       - { nilTotal, scholarships }
 * @param {Array}    opts.players        - Already-assembled player list.
 *   Each player must have: name, pos, year, height, nilOffer, stats, _type
 *   _type is one of "Returning" | "Undecided" | "Transfer In"
 */
export function exportRosterPDF({ team, settings, players }) {
  const returning  = players.filter(p => p._type !== "Transfer In");
  const transfers  = players.filter(p => p._type === "Transfer In");
  const totalNil   = players.reduce((s, p) => s + (p.nilOffer || 0), 0);

  const badgeClass = type => {
    if (type === "Transfer In") return "transfer";
    if (type === "Undecided")   return "undecided";
    return "returning";
  };

  function row(p) {
    const s = p.stats || {};
    const nilCell = p.nilOffer > 0 ? `$${Number(p.nilOffer).toLocaleString()}` : "—";
    const badge = `<span class="badge ${badgeClass(p._type)}">${p._type}</span>`;
    return `
      <tr>
        <td><strong>${p.name}</strong> ${badge}</td>
        <td>${p.pos || "—"}</td>
        <td>${p.year || "—"}</td>
        <td>${p.height || "—"}</td>
        <td>${fmtStat(s.ppg,     "ppg")}</td>
        <td>${fmtStat(s.rpg,     "rpg")}</td>
        <td>${fmtStat(s.apg,     "apg")}</td>
        <td>${fmtStat(s.fg_pct,  "fg_pct")}</td>
        <td>${fmtStat(s["3p_pct"], "3p_pct")}</td>
        <td>${fmtStat(s.ft_pct,  "ft_pct")}</td>
        <td>${nilCell}</td>
      </tr>`;
  }

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>${team || "Roster"} — Beyond the Portal</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #111; background: #fff; padding: 32px 40px; }
  h1 { font-size: 22px; font-weight: 700; margin-bottom: 2px; }
  .sub { font-size: 13px; color: #555; margin-bottom: 20px; }
  .summary { display: flex; gap: 28px; margin-bottom: 18px; flex-wrap: wrap; }
  .sum-item .lbl { font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #888; }
  .sum-item .val { font-size: 16px; font-weight: 700; margin-top: 1px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  thead tr { background: #1a2a3a; color: #fff; }
  thead th { padding: 8px 10px; text-align: left; font-weight: 600; white-space: nowrap; }
  tbody tr:nth-child(even) { background: #f5f7fa; }
  tbody td { padding: 7px 10px; border-bottom: 1px solid #e5e8ed; vertical-align: middle; }
  .badge { display: inline-block; font-size: 9px; font-weight: 700; text-transform: uppercase;
           letter-spacing: .04em; padding: 2px 6px; border-radius: 10px; margin-left: 5px; vertical-align: middle; }
  .badge.returning { background: #dcfce7; color: #166534; }
  .badge.undecided { background: #fef9c3; color: #854d0e; }
  .badge.transfer  { background: #dbeafe; color: #1d4ed8; }
  .footer { margin-top: 18px; display: flex; justify-content: space-between; font-size: 11px; color: #777; border-top: 1px solid #ddd; padding-top: 10px; }
  @media print {
    body { padding: 16px 20px; }
    @page { margin: 1.5cm; size: letter landscape; }
  }
</style>
</head>
<body>
  <h1>${team || "Program"} — Projected Roster</h1>
  <div class="sub">Generated by Beyond the Portal · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</div>
  <div class="summary">
    <div class="sum-item"><div class="lbl">Total Players</div><div class="val">${players.length}</div></div>
    <div class="sum-item"><div class="lbl">Returning</div><div class="val">${returning.length}</div></div>
    <div class="sum-item"><div class="lbl">Transfers In</div><div class="val">${transfers.length}</div></div>
    <div class="sum-item"><div class="lbl">NIL Committed</div><div class="val">$${totalNil.toLocaleString()}</div></div>
    <div class="sum-item"><div class="lbl">NIL Budget</div><div class="val">$${Number(settings?.nilTotal || 0).toLocaleString()}</div></div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Player</th><th>Pos</th><th>Yr</th><th>Ht</th>
        <th>PPG</th><th>RPG</th><th>APG</th>
        <th>FG%</th><th>3P%</th><th>FT%</th>
        <th>NIL Offer</th>
      </tr>
    </thead>
    <tbody>
      ${players.map(row).join("")}
    </tbody>
  </table>
  <div class="footer">
    <span>Beyond the Portal · beyondtheportal.com</span>
    <span>${players.length} players · NIL Budget: $${Number(settings?.nilTotal || 0).toLocaleString()}</span>
  </div>
  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`;

  const win = window.open("", "_blank");
  win.document.write(html);
  win.document.close();
}
