-- ============================================================
-- Extend vw_players / vw_w_players to expose player_status and the new
-- transfer_* fields (added in add_transfer_fields.sql).
--
-- Neither view previously exposed player_status at all — useRosterBoard.js
-- worked around this with a second query straight against the base table.
-- Adding it here (plus the transfer_* fields) lets board/rankings/roster
-- code read everything off one row instead of a second round-trip.
--
-- New columns are appended at the end of each SELECT list — Postgres
-- requires CREATE OR REPLACE VIEW to preserve existing column order/types,
-- appending is the only safe way to extend without a drop+recreate.
--
-- Safe to run more than once.
-- ============================================================

create or replace view public.vw_players as
 SELECT p.id,
    p.name,
    p.current_team,
    p.primary_position,
    p.year,
    p.height,
    p.hometown,
    p.espn_id,
    p.source,
    p.open_market_low,
    p.open_market_high,
    p.nil_valuation,
    s.ppg,
    s.rpg,
    s.apg,
    s.usg,
    s.ast_tov,
    s.fg_pct,
    s."3p_pct",
    s.ft_pct,
    s.sei,
    s.ath,
    s.ris,
    s.dds,
    s.cdi,
    s.conference,
    s.calendar_year,
    p.player_status,
    p.transfer_status,
    p.transfer_from_team,
    p.transfer_to_team,
    p.transfer_season_year,
    p.transfer_api_id,
    p.positions
   FROM players p
     LEFT JOIN LATERAL ( SELECT player_stats.id,
            player_stats.player_id,
            player_stats.year,
            player_stats.ppg,
            player_stats.rpg,
            player_stats.apg,
            player_stats."3pg",
            player_stats.usg,
            player_stats.ast_tov,
            player_stats.fg_pct,
            player_stats.ft_pct,
            player_stats."3p_pct",
            player_stats.atr_pct,
            player_stats.stl_40,
            player_stats.blk_40,
            player_stats.drb_40,
            player_stats.orb_40,
            player_stats.trb_40,
            player_stats.cdi,
            player_stats.dds,
            player_stats.sei,
            player_stats.smi,
            player_stats.ris,
            player_stats.created_at,
            player_stats.calendar_year,
            player_stats.name,
            player_stats.torvik_ortg,
            player_stats.torvik_usg,
            player_stats.torvik_efg,
            player_stats.torvik_ts,
            player_stats.torvik_obpm,
            player_stats.torvik_dbpm,
            player_stats.torvik_bpm,
            player_stats.torvik_drtg,
            player_stats.torvik_stops,
            player_stats.torvik_ast_pct,
            player_stats.torvik_to_pct,
            player_stats.torvik_orb_pct,
            player_stats.torvik_drb_pct,
            player_stats.torvik_rim_pct,
            player_stats.torvik_mid_pct,
            player_stats.torvik_3p_pct,
            player_stats.torvik_porpag,
            player_stats.torvik_adjoe,
            player_stats.torvik_min_pct,
            player_stats.torvik_gp,
            player_stats.ast_40,
            player_stats.tot_g,
            player_stats.tot_gs,
            player_stats.tot_mp,
            player_stats.tot_fg,
            player_stats.tot_fga,
            player_stats.tot_3p,
            player_stats.tot_3pa,
            player_stats.tot_2p,
            player_stats.tot_2pa,
            player_stats.tot_ft,
            player_stats.tot_fta,
            player_stats.tot_orb,
            player_stats.tot_drb,
            player_stats.tot_trb,
            player_stats.tot_ast,
            player_stats.tot_stl,
            player_stats.tot_blk,
            player_stats.tot_tov,
            player_stats.tot_pf,
            player_stats.tot_pts,
            player_stats.school,
            player_stats.conference,
            player_stats.ath,
            player_stats.projected_tier,
            player_stats.nil_perf_score
           FROM player_stats
          WHERE player_stats.player_id = p.id
          ORDER BY player_stats.calendar_year DESC NULLS LAST
         LIMIT 1) s ON true;

create or replace view public.vw_w_players as
 SELECT p.id,
    p.name,
    p.current_team,
    p.primary_position,
    p.year,
    p.height,
    p.hometown,
    p.source,
    p.espn_id,
    p.eligibility_years,
    p.archetype,
    p.nil_valuation,
    p.open_market_low,
    p.open_market_high,
    s.year AS calendar_year,
    s.ppg,
    s.rpg,
    s.apg,
    s.usg,
    s.ast_tov,
    s.fg_pct,
    s."3p_pct",
    s.ft_pct,
    s.sei,
    s.ath,
    s.ris,
    s.dds,
    s.cdi,
    s.school,
    s.conference,
    p.archetype_overwrite,
    p.player_status,
    p.transfer_status,
    p.transfer_from_team,
    p.transfer_to_team,
    p.transfer_season_year,
    p.transfer_api_id,
    p.positions
   FROM w_players p
     LEFT JOIN LATERAL ( SELECT ps.id,
            ps.player_id,
            ps.year,
            ps.ppg,
            ps.rpg,
            ps.apg,
            ps."3pg",
            ps.usg,
            ps.ast_tov,
            ps.fg_pct,
            ps.ft_pct,
            ps."3p_pct",
            ps.atr_pct,
            ps.stl_40,
            ps.blk_40,
            ps.drb_40,
            ps.orb_40,
            ps.trb_40,
            ps.cdi,
            ps.dds,
            ps.sei,
            ps.smi,
            ps.ris,
            ps.created_at,
            ps.calendar_year,
            ps.name,
            ps.torvik_ortg,
            ps.torvik_usg,
            ps.torvik_efg,
            ps.torvik_ts,
            ps.torvik_obpm,
            ps.torvik_dbpm,
            ps.torvik_bpm,
            ps.torvik_drtg,
            ps.torvik_stops,
            ps.torvik_ast_pct,
            ps.torvik_to_pct,
            ps.torvik_orb_pct,
            ps.torvik_drb_pct,
            ps.torvik_rim_pct,
            ps.torvik_mid_pct,
            ps.torvik_3p_pct,
            ps.torvik_porpag,
            ps.torvik_adjoe,
            ps.torvik_min_pct,
            ps.torvik_gp,
            ps.ast_40,
            ps.tot_g,
            ps.tot_gs,
            ps.tot_mp,
            ps.tot_fg,
            ps.tot_fga,
            ps.tot_3p,
            ps.tot_3pa,
            ps.tot_2p,
            ps.tot_2pa,
            ps.tot_ft,
            ps.tot_fta,
            ps.tot_orb,
            ps.tot_drb,
            ps.tot_trb,
            ps.tot_ast,
            ps.tot_stl,
            ps.tot_blk,
            ps.tot_tov,
            ps.tot_pf,
            ps.tot_pts,
            ps.school,
            ps.conference,
            ps.ath,
            ps.projected_tier,
            ps.nil_perf_score,
            ps.torvik_blk_pct,
            ps.torvik_stl_pct,
            ps.torvik_ftr,
            ps.torvik_pfr,
            ps.torvik_adrtg,
            ps.torvik_dporpag,
            ps.torvik_ogbpm,
            ps.torvik_dgbpm,
            ps.torvik_gbpm,
            ps.torvik_rec_rank
           FROM w_player_stats ps
          WHERE ps.player_id = p.id
          ORDER BY ps.year DESC NULLS LAST
         LIMIT 1) s ON true;

notify pgrst, 'reload schema';
